catalog:
  name: "drone"
  version: "v0.1"
  description: "Real-time performance tracking and visualization of your container-based application deployment"
  minimum_sry_version: v0.46.0
  questions:
    - variable: "api_key"
      label: "这是一个字符串"
      description: "这是一个字符串,必填"
      required: true
      type: "string"
    - variable: "host_labels"
      label: "这是一个字符串"
      description: "这是一个字符串选填"
      required: false
      type: "string"
    - variable: "global_service"
      label: "这一个radio"
      description: "这是一个radio，可选项为true或者false"
      required: true
      type: "boolean"
      default: true
    - variable: "select_value"
      label: "这一个下拉框"
      description: "这是一个下拉框"
      required: true
      type: "enum"
      options:
        - "foo"
        - "bar"
      default: "foo"
drone:
  image:  devregistry.dataman-inc.com:5000/library/drone
  restart: always
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/drone:/var/lib/drone
  ports:
    - "8080"
